Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace la_mia_pizzeria_crud_webapi.Models;

public class Pizza
{
    public int Id { get; set; }
    
    [Required(ErrorMessage = "{0} is required.")]
    [StringLength(30, ErrorMessage = "{0} must contain a maximum of {1} characters.")]
    public string Name { get; set; } = null!;
    
    [Required(ErrorMessage = "{0} is required.")]
    [RegularExpression(@"(\w+\s){4,}\w+", ErrorMessage = "{0} must contains at least 5 words.")]
    public string Description { get; set; } = null!;
    
    [Required(ErrorMessage = "{0} is required.")]
    [Url(ErrorMessage = "{0} is not a valid url.")]
    public string Photo { get; set; } = null!;
    
    [Required(ErrorMessage = "{0} is required.")]
    [DataType(DataType.Currency)]
    [Column(TypeName = "money")]
    [Range(0, 100, ErrorMessage = "{0} must be between {1:C} and {2:C}.")]
    public decimal Price { get; set; }
    
    public int CategoryId { get; set; }
    [JsonIgnore]
    public Category? Category { get; set; }
    
    [JsonIgnore]
    public virtual ICollection<Ingredient>? Ingredients { get; set; }
}

Models/PizzaViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace la_mia_pizzeria_crud_webapi.Models;

public class PizzaViewModel
{
    public PizzaViewModel()
    {
        Categories = new List<SelectListItem>();
        IngredientIds = new List<int>();
        Ingredients = new List<SelectListItem>();
    }
    
    public Pizza Pizza { get; set; } = null!;
    public IEnumerable<SelectListItem> Categories { get; set; }
    public IEnumerable<int> IngredientIds { get; set; }
    public IEnumerable<SelectListItem> Ingredients { get; set; }
}

Controllers/Api/PizzasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using la_mia_pizzeria_crud_webapi.Data;
using la_mia_pizzeria_crud_webapi.Interfaces;
using la_mia_pizzeria_crud_webapi.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace la_mia_pizzeria_crud_webapi.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class PizzasController : ControllerBase
    {
        private readonly IUnitOfWork _unitOfWork;

        public PizzasController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Get(string? name)
        {
            var pizzas = _unitOfWork.Pizza.GetAll();
            
            if (name is not null)
            {
                pizzas = pizzas.Where(x => x.Name.ToLower().Contains(name.ToLower()));
            }
            
            return Ok(pizzas.ToList());
        }

        [HttpGet]
        [Route("{id:int}")]
        public IActionResult Get(int id)
        {
            var pizza = _unitOfWork.Pizza.GetFirstOrDefault(x => x.Id == id);

            if (pizza is null)
            {
                return NotFound();
            }

            return Ok(pizza);
        }

        [HttpPut]
        [Route("{id:int}")]
        public IActionResult Put(int id, Pizza pizza)
        {
            if (id != pizza.Id)
            {
                return BadRequest();
            }
            
            if (!_unitOfWork.Pizza.Exists(x => x.Id == id))
            {
                return NotFound();
            }
            
            _unitOfWork.Pizza.Update(pizza, Enumerable.Empty<Ingredient>());
            _unitOfWork.Save();

            return NoContent();
        }
        
        [HttpDelete]
        [Route("{id:int}")]
        public IActionResult Delete(int id)
        {
            var pizza = _unitOfWork.Pizza.GetFirstOrDefault(x => x.Id == id);
            
            if (pizza is null)
            {
                return NotFound();
            }

            _unitOfWork.Pizza.Remove(pizza);
            _unitOfWork.Save();

            return NoContent();
        }
    }
}

Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using la_mia_pizzeria_crud_webapi.Data;
using la_mia_pizzeria_crud_webapi.Interfaces;
using la_mia_pizzeria_crud_webapi.Models;
using la_mia_pizzeria_crud_webapi.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace la_mia_pizzeria_crud_webapi.Controllers;

[Authorize]
public class PizzaController : Controller
{
    private readonly ApplicationDbContext _ctx;
    private readonly IUnitOfWork _unitOfWork;
    
    public PizzaController(ApplicationDbContext ctx, IUnitOfWork unitOfWork)
    {
        _ctx = ctx;
        _unitOfWork = unitOfWork;
    }

    // GET
    public IActionResult Index()
    {
        var pizzas = 
            _unitOfWork.Pizza.GetAll("Category,Ingredients");
        return View(pizzas);
    }
    
    // GET: Pizza/Details/{id?}
    public IActionResult Details(int? id)
    {
        if (id is null or 0)
        {
            return NotFound();
        }
        
        var pizza = 
            _unitOfWork.Pizza
                .GetFirstOrDefault(
                    x => x.Id == id, 
                    "Category,Ingredients");

        if (pizza is null)
        {
            return NotFound();
        }
        
        return View(pizza);
    }
    
    // GET: Pizza/Create
    public IActionResult Create()
    {
        var pizzaVm = GetViewModelWithDropDownLists();
        return View(pizzaVm);
    }
    
    // POST: Pizza/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(PizzaVm pizzaVm)
    {
        if (!ModelState.IsValid)
        {
            return View(pizzaVm);
        }

        var pizza = pizzaVm.Pizza;

        pizza.Ingredients =
            _unitOfWork.Ingredient
                .GetSelectedIngredients(pizzaVm.SelectedIngredients)
                .ToList();

        _unitOfWork.Pizza.Add(pizza);
        _unitOfWork.Save();
        
        return RedirectToAction(nameof(Index));
    }
    
    // GET: Pizza/Edit/{id?}
    public IActionResult Edit(int? id)
    {
        if (id is null or 0)
        {
            return NotFound();
        }
        
        var pizza = 
            _unitOfWork.Pizza
                .GetFirstOrDefault(
                    x => x.Id == id, 
                    "Ingredients");

        if (pizza is null)
        {
            return NotFound();
        }
        
        var pizzaVm = GetViewModelWithDropDownLists();
        pizzaVm.Pizza = pizza;
        pizzaVm.SelectedIngredients = pizza.Ingredients!.Select(x => x.Id);
        
        return View(pizzaVm);
    }
    
    // POST: Pizza/Edit/{id?}
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(PizzaVm pizzaVm)
    {
        if (!ModelState.IsValid)
        {
            return View(pizzaVm);
        }
        
        var ingredients = 
            _unitOfWork.Ingredient
                .GetSelectedIngredients(pizzaVm.SelectedIngredients)
                .ToList();

        _unitOfWork.Pizza.Update(pizzaVm.Pizza, ingredients);
        _unitOfWork.Save();
        
        return RedirectToAction(nameof(Index));
    }
    
    // POST: Pizza/Delete/{id?}
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(int? id)
    {
        if (id is null or 0)
        {
            return NotFound();
        }
        
        var pizza = _unitOfWork.Pizza.GetFirstOrDefault(x => x.Id == id);

        if (pizza is null)
        {
            return NotFound();
        }
        
        _unitOfWork.Pizza.Remove(pizza);
        _unitOfWork.Save();
        
        return RedirectToAction(nameof(Index));
    }

    private PizzaVm GetViewModelWithDropDownLists()
    {
        return new PizzaVm
        {
            Pizza = new Pizza(), 
            Categories = _unitOfWork.Category.GetSelectListItem(),
            Ingredients = _unitOfWork.Ingredient.GetSelectListItem()
        };
    }
}

Views/Pizza/Create.cshtml
@model la_mia_pizzeria_crud_webapi.Models.ViewModels.PizzaVm

@{
    ViewData["Title"] = "Create New Pizza";
}

<div class="container py-1">
    <div class="row pb-4">
        <div class="col-md-6">
            <h2>Create New Pizza</h2>
        </div>
    </div>
    
    <form method="POST" asp-controller="Pizza" asp-action="Create" class="card bg-light has-validation">
        <div class="card-body">
            <div class="row g-3">
                <div class="col-12">
                    <label asp-for="Pizza.Category" class="form-label">Category</label>
                    <select asp-for="Pizza.CategoryId" asp-items="Model.Categories" class="form-select">
                        <option disabled selected>-- Select a Category --</option>
                    </select>
                    <span asp-validation-for="Pizza.CategoryId"></span>
                </div>
                
                <div class="col-md-6">
                    <label asp-for="Pizza.Name" class="form-label">Name</label>
                    <input asp-for="Pizza.Name" type="text" class="form-control">
                    <span asp-validation-for="Pizza.Name"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Pizza.Price" class="form-label">Price</label>
                    <input asp-for="Pizza.Price" type="number" min="0" max="100" value="0" step=".50" class="form-control">
                    <span asp-validation-for="Pizza.Price"></span>
                </div>

                <div class="col-12">
                    <label asp-for="Pizza.Photo" class="form-label">Photo</label>
                    <input asp-for="Pizza.Photo" type="text" class="form-control">
                    <span asp-validation-for="Pizza.Photo"></span>
                </div>

                <div class="col-12">
                    <label asp-for="Pizza.Description" class="form-label">Description</label>
                    <textarea asp-for="Pizza.Description" rows="3" class="form-control"></textarea>
                    <span asp-validation-for="Pizza.Description"></span>
                </div>
                
                <div class="col-12">
                    <label asp-for="SelectedIngredients" class="form-label">Ingredients</label>
                    <select asp-for="SelectedIngredients" asp-items="Model.Ingredients" class="form-select" multiple size="6">
                    </select>
                </div>

                <div class="col-12">
                    <button type="submit" class="btn btn-primary">
                        Create
                    </button>
                    <a asp-controller="Pizza" asp-action="Index" type="button" class="btn btn-secondary">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Pizza/Details.cshtml
@model Pizza

@{
  ViewData["Title"] = "Details";
}

<div class="card bg-light fs-4">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="@Model.Photo" class="img-fluid rounded-start" alt="@Model.Name">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h2 class="card-title">@Model.Name</h2>
        <p class="card-text">
          <span class="badge bg-primary">@Model.Category!.Name</span>
        </p>
        <p class="card-text">
          @Model.Description
        </p>
        @if (Model.Ingredients.Any())
        {
          <p class="card-text">
            <span>Ingredients:</span>
            
            <ul>
              @foreach (var ingredient in Model.Ingredients)
              {
                <li>@ingredient.Name</li>
              }
            </ul>
          </p>
        }
        <p class="card-text text-end">
          Price:
          <small class="text-muted">@Model.Price.ToString("C")</small>
        </p>
      </div>
    </div>
  </div>
</div>

Views/Pizza/Edit.cshtml
@model la_mia_pizzeria_crud_webapi.Models.ViewModels.PizzaVm

@{
    ViewData["Title"] = "Edit a Pizza";
}

<div class="container py-1">
    <div class="row pb-4">
        <div class="col-md-6">
            <h2>Edit @Model.Pizza.Name</h2>
        </div>
    </div>
    
    <form method="POST" asp-controller="Pizza" asp-action="Edit" asp-route-id="@Model.Pizza.Id" class="card bg-light has-validation">
        <div class="card-body">
            <div class="row g-3">
                <input type="hidden" asp-for="Pizza.Id" />
                
                <div class="col-12">
                    <label asp-for="Pizza.Category" class="form-label">Category</label>
                    <select asp-for="Pizza.CategoryId" asp-items="Model.Categories" class="form-select">
                        <option disabled selected>-- Select a Category --</option>
                    </select>
                    <span asp-validation-for="Pizza.CategoryId"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Pizza.Name" class="form-label">Name</label>
                    <input asp-for="Pizza.Name" type="text" class="form-control">
                    <span asp-validation-for="Pizza.Name"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Pizza.Price" class="form-label">Price</label>
                    <input asp-for="Pizza.Price" type="number" min="0" max="100" value="@Model.Pizza.Price.ToString("###.##")" step=".50" class="form-control">
                    <span asp-validation-for="Pizza.Price"></span>
                </div>

                <div class="col-12">
                    <label asp-for="Pizza.Photo" class="form-label">Photo</label>
                    <input asp-for="Pizza.Photo" type="text" class="form-control">
                    <span asp-validation-for="Pizza.Photo"></span>
                </div>

                <div class="col-12">
                    <label asp-for="Pizza.Description" class="form-label">Description</label>
                    <textarea asp-for="Pizza.Description" rows="3" class="form-control"></textarea>
                    <span asp-validation-for="Pizza.Description"></span>
                </div>
                
                <div class="col-12">
                    <label asp-for="SelectedIngredients" class="form-label">Ingredients</label>
                    <select asp-for="SelectedIngredients" asp-items="Model.Ingredients" class="form-select" multiple size="6">
                    </select>
                </div>

                <div class="col-12">
                    <button type="submit" class="btn btn-primary">
                        Update
                    </button>
                    <a asp-controller="Pizza" asp-action="Index" type="button" class="btn btn-secondary">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Pizza/Index.cshtml
@model IEnumerable<Pizza>

@{
    ViewData["Title"] = "Home";
}

<div class="py-1">
  <div class="container">
    <div class="row pb-4">
      <div class="col-6">
        <a asp-controller="Pizza" asp-action="Create" type="button" class="btn btn-primary">
          <i class="bi bi-plus-circle"></i> &nbsp; Create New Pizza
        </a>
      </div>
    </div>
    

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      @foreach (var pizza in Model)
      {
        <div class="col">
          <div class="card shadow-sm">
            <img src="@pizza.Photo" alt="@pizza.Name" width="100%" height="225">

            <div class="card-body">
              <h3>@pizza.Name</h3>
              <p class="card-text">
                <span class="badge bg-primary">@pizza.Category!.Name</span>
              </p>
              <p class="card-text">
                @pizza.Description
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a asp-controller="Pizza" asp-action="Details" asp-route-id="@pizza.Id" type="button" class="btn btn-sm btn-info">
                    <i class="bi bi-eye"></i> &nbsp; View
                  </a>
                  <a asp-controller="Pizza" asp-action="Edit" asp-route-id="@pizza.Id" type="button" class="btn btn-sm btn-warning">
                    <i class="bi bi-pencil-square"></i> &nbsp; Edit
                  </a>
                  <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal_@pizza.Id">
                    <i class="bi bi-trash3"></i> &nbsp; Delete
                  </button>
                </div>
                <small class="text-muted">@pizza.Price.ToString("C")</small>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="deleteModal_@pizza.Id" tabindex="-1" aria-labelledby="deleteModal_@(pizza.Id)_Label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModal_@(pizza.Id)_Label">Confirm deletion</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                Are you sure you want to delete the category <span class="text-primary fw-bold">@pizza.Name</span>?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                  <i class="bi bi-arrow-left-circle"></i> &nbsp; Back
                </button>
                <form method="POST" asp-controller="Pizza" asp-action="Delete" asp-route-id="@pizza.Id">
                  <button type="submit" class="btn btn-danger">
                    <i class="bi bi-trash3"></i> &nbsp; Delete
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      }
    </div>
  </div>
</div>